### ISSUE TITLE
Rename join to concat

### ISSUE THREAD

**Issue by beilharz** [witheve/docs#22]
It seems "join" was renamed to "concat" at one point, that should be reflected in the docs. 

I don't understand how concat is meant to work, any attempts i did only result in builder complaining that it can't find the AttributeMapping (because there isn't any defined in string.ts). 
Can concat actually be used in it's current state?

**Comment by cmontella** [comment]
Join actually serves a different purpose from concat, although it isn't actually implemented in this runtime yet (although maybe I'll do that shortly)

The purpose of join in this context is more like: http://www.w3schools.com/jsref/jsref_join.asp

You take an set of strings, an ordering of those elements, and then combine them into a single string, separated by some delimiter.

for example if  token = ("A","B","C","D") and index = (1,3,2,4) and with = "--" then `join[token, index, with]` would produce "A--C--B--D"

The reason you can't use concat is because you're not meant to use it with the string interpolation operator `{{}}`. You can embed any value in a string with this operator:

```
search
  [name]

bind @browser
  [#div text: "Welcome, {{name}}!"]
```

Hope this helps!

**Comment by beilharz** [comment]
Ok – Thanks for clarifying this. 

I actually think concat is the better name, given the importance of records in eve and the different meaning of joins in the database world...
